# coding: utf-8
import random

colors = [
    "Aero", "Almond", "Amaranth", "Amazon", "Amber",
    "AmethystApricot", "Aqua", "Aquamarine", "Arsenic", "Artichoke",
    "Asparagus", "Auburn", "Aureolin", "AuroMetalSaurus", "Avocado",
    "Azure", "Bazaar", "Beaver", "Beige", "Bisque",
    "Bistre", "Bittersweet", "Black", "Blond", "Blue",
    "BlueGray", "BlueGreen", "BlueViolet", "Blueberry", "Bluebonnet",
    "Blush", "Bole", "Bone", "Boysenberry", "Brass",
    "Bronze", "BrownNose", "Bubbles", "Buff", "Burgundy",
    "Burlywood", "Byzantine", "Byzantium", "Cadet", "Camel",
    "Capri", "Cardinal", "Carmine", "Carnelian", "Catawba",
    "Ceil", "Celadon", "Celeste", "Cerise", "Cerulean",
    "Chamoisee", "Champagne", "Charcoal", "Cherry", "Chestnut",
    "Cinereous", "Cinnabar", "Cinnamon", "Citrine", "Citron",
    "Claret", "Coconut", "Coffee", "Copper", "Coquelicot",
    "Coral", "Cordovan", "Corn", "Cornsilk", "Cream",
    "Crimson", "Cyan", "Daffodil", "Dandelion", "Deer",
    "Denim", "Desert", "Desire", "Diamond", "Dirt",
    "Drab", "Ebony", "Ecru", "Eggplant", "Eggshell",
    "Emerald", "Eminence", "Eucalyptus", "Fallow", "Fandango",
    "Fawn", "Feldgrau", "Feldspar", "Firebrick", "Flame",
    "Flattery", "Flavescent", "Flax", "Flirt", "Folly",
    "Fuchsia", "Fulvous", "Gainsboro", "Gamboge", "Ginger",
    "Glaucous", "Glitter", "Goldenrod", "Grape", "Gray",
    "GrayAsparagus", "GrayBlue", "GreenBlue", "GreenCyan", "GreenYellow",
    "Grizzly", "Grullo", "Gunmetal", "Harlequin", "Heliotrope",
    "Honeydew", "Iceberg", "Icterine", "Imperial", "Inchworm",
    "Independence", "Indigo", "Iris", "Irresistible", "Isabelline",
    "Ivory", "Jade", "Jasmine", "Jasper", "Jet",
    "Jonquil", "Keppel", "Kobe", "Kobi", "Kobicha",
    "Lava", "Lemon", "Lenurple", "Liberty", "Licorice",
    "Lilac", "Limerick", "Linen", "Lion", "Liver",
    "Livid", "Lumber", "Magenta", "MagentaPink", "Magnolia",
    "Mahogany", "Maize", "Malachite", "Manatee", "Mantis",
    "Mauve", "Mauvelous", "Melon", "Mindaro", "Ming",
    "Mint", "MoccasinMulberry", "Mustard", "NavyNyanza", "Ochre",
    "Olive", "Olivine", "Onyx", "OrangeRed", "Orchid",
    "Patriarch", "Peach", "PeachOrange", "PeachYellow", "Pear",
    "Pearl", "Peridot", "PeriwinklePersimmon", "Peru", "Phlox",
    "Pineapple", "Pink", "PinkOrange", "Pistachio", "Platinum",
    "Plum", "Popstar", "Prune", "Puce", "Pumpkin",
    "Purpureus", "Quartz", "Rackley", "Rajah", "Raspberry",
    "Razzmatazz", "Red", "RedBrown", "RedOrange", "RedPurple",
    "RedViolet", "Redwood", "Regalia", "Rhythm", "RoseRosewoodRuber",
    "Ruby", "Ruddy", "Rufous", "Russet", "Rust",
    "Saffron", "Sage", "Salmon", "Sand", "Sandstorm",
    "Sangria", "Sapphire", "Scarlet", "Seashell", "Sepia",
    "Shadow", "Shampoo", "Sienna", "Silver", "Sinopia",
    "Skobeloff", "Smitten", "Smoke", "Snow", "Soap",
    "Stizza", "Stormcloud", "Straw", "Strawberry", "Sunglow",
    "Sunray", "Sunset", "Tan", "Tangelo", "Tangerine",
    "Taupe", "Teal", "Telemagenta", "Tenné", "Thistle",
    "Timberwolf", "Tomato", "Toolbox", "Topaz", "Tulip",
    "Tumbleweed", "Turquoise", "Tuscan", "Tuscany", "Ube",
    "Ultramarine", "Umber", "Urobilin", "Vanilla", "Verdigris",
    "Vermilion", "Veronica", "Violet", "VioletBlue", "VioletRed",
    "Viridian", "Volt", "Waterspout", "Wenge", "Wheat",
    "White", "Wine", "Wisteria", "Xanadu", "Yellow",
    "YellowGreen", "Zaffre", "Zomp"]
fruits = [
    "Apple",  "Apricot",  "Avocado",  "Banana",  "Bilberry",
    "Blackberry",  "Blackcurrant",  "Blueberry",  "Boysenberry",  "Cantaloupe",
    "Currant",  "Cherry",  "Cherimoya",  "Cloudberry",  "Coconut",
    "Cranberry",  "Damson",  "Date",  "Dragonfruit",  "Durian",
    "Elderberry",  "Feijoa",  "Fig",  "Gojiberry",  "Gooseberry",
    "Grape",  "Raisin",  "Grapefruit",  "Guava",  "Huckleberry",
    "Jabouticaba",  "Jackfruit",  "Jambul",  "Jujube",  "Juniperberry",
    "Kiwifruit",  "Kumquat",  "Lemon",  "Lime",  "Loquat",
    "Lychee",  "Mango",  "Marionberry",  "Melon",  "Cantaloupe",
    "Honeydew",  "Watermelon",  "Rockmelon",  "Miraclefruit",  "Mulberry",
    "Nectarine",  "Olive",  "Orange",  "BloodOrange",  "Clementine",
    "Mandarine",  "Tangerine",  "Papaya",  "Passionfruit",  "Peach",
    "Pear",  "Williamspear",  "Bartlettpear",  "Persimmon",  "Physalis",
    "Plum",  "Pineapple",  "Pomegranate",  "Pomelo",  "PurpleMangosteen",
    "Quince",  "Raspberry",  "Salmonberry",  "Blackraspberry",  "Rambutan",
    "Redcurrant",  "Salalberry",  "Satsuma",  "Starfruit",  "Strawberry",
    "Tamarillo", "Uglifruit"]

print(random.choice(colors)+random.choice(fruits))

